# CircleCI 2.0 configuration file
version: 2.1

orbs:
  codacy: codacy/base@2.1.1
  codacy_plugins_test: codacy/plugins-test@0.8.0

jobs:
  test:
    machine: true
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/workdir
      - run:
          name: Install the tool
          command: |
            sudo apt-get -y update
            sudo apt-get -y install ruby-full
            sudo gem install bundler -v 1.17.3
            bundle install
      - run:
          name: Test
          command: scripts/test.sh
      - run:
          name: Store test reports
          command: |
            mkdir -p coverage-reports/scoverage
            cp -f target/scala-2.12/coverage-report/cobertura.xml coverage-reports/scoverage/results.xml
      - store_test_results:
          path: coverage-reports
      - store_artifacts:
          path: target/scala-2.12/coverage-report
      - store_artifacts:
          path: target/scala-2.12/scoverage-report
      - store_artifacts:
          path: target/scala-2.12/scoverage-data

workflows:
  version: 2
  test_and_publish:
    jobs:
      - codacy/checkout_and_version
      - codacy/sbt:
          name: sbt_dependencies
          cmd: |
            sbt update
          persist_to_workspace: true
          requires:
            - codacy/checkout_and_version
      - codacy/sbt:
          name: compile
          cmd: |
            sbt ";compile;test:compile"
          persist_to_workspace: true
          requires:
            - codacy/checkout_and_version
            - sbt_dependencies
      - test:
          requires:
            - compile
      - codacy/sbt:
          name: lint
          cmd: |
            sbt "set scalafmtUseIvy in ThisBuild := false;
                 scalafmt::test;
                 test:scalafmt::test;
                 sbt:scalafmt::test;
                 scapegoat;
                 scalafixCli --test"
          requires:
            - compile
      - codacy/sbt:
          name: publish_docker_local
          cmd: |
            sbt "set version in Docker := \"latest\";
                 docker:publishLocal"
            docker save --output docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
          persist_to_workspace: true
          requires:
            - compile
            - codacy/checkout_and_version
      - codacy_plugins_test/run:
          name: plugins_test
          run_json_tests: false
          requires:
            - publish_docker_local
      - codacy/shell:
          name: publish_dockerhub
          context: CodacyDocker
          cmd: |
            docker load --input docker-image.tar
            docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
            docker tag "$CIRCLE_PROJECT_REPONAME" "codacy/$CIRCLE_PROJECT_REPONAME:$(cat .version)"
            docker tag "$CIRCLE_PROJECT_REPONAME" "codacy/$CIRCLE_PROJECT_REPONAME:latest"
            docker push "codacy/$CIRCLE_PROJECT_REPONAME:$(cat .version)"
            docker push "codacy/$CIRCLE_PROJECT_REPONAME:latest"
          requires:
            - test
            - lint
            - publish_docker_local
          filters:
            branches:
              only:
                - master
