version: 2.1

orbs:
  codacy: codacy/base@10.2.2
  codacy_plugins_test: codacy/plugins-test@1.1.1

workflows:
  version: 2
  test_and_publish:
    jobs:
      - codacy/checkout_and_version
      - codacy/sbt:
          name: sbt_dependencies
          cmd: |
            sbt update
          persist_to_workspace: true
          requires:
            - codacy/checkout_and_version
      - codacy/sbt:
          name: compile
          cmd: |
            sbt ";compile;test:compile"
          persist_to_workspace: true
          requires:
            - codacy/checkout_and_version
            - sbt_dependencies
      - codacy/sbt:
          name: lint
          cmd: |
            sbt "set scalafmtUseIvy in ThisBuild := false;
                 scalafmt::test;
                 test:scalafmt::test;
                 sbt:scalafmt::test;
                 scapegoat;
                 scalafixCli --test"
          requires:
            - compile
      - codacy/sbt:
          name: publish_docker_local
          cmd: |
            sbt "set version in Docker := \"latest\";
                 docker:publishLocal"
            docker save --output docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
          persist_to_workspace: true
          requires:
            - compile
            - codacy/checkout_and_version
      - codacy_plugins_test/run:
          name: plugins_test
          run_json_tests: false
          run_duplication_tests: true
          requires:
            - publish_docker_local
      - codacy/publish_docker:
          context: CodacyDocker
          requires:
            - lint
            - plugins_test
            - publish_docker_local
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
           name: tag_version
           context: CodacyAWS
           requires:
             - codacy/publish_docker
